markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 阿曹的曹
host: cxlcym.github.com
desc: 有家咖啡馆叫阿曹的曹

custom:
    category:
        thinking: 思考总结
        problems: 问题记录
        knowledge: 知识经验
        discovery: 新的发现
    categories:
      - name: thinking
        title: 思考总结

      - name: problems
        title: 问题记录

      - name: knowledge
        title: 知识经验

      - name: discovery
        title: 新的发现

meta:
    author:
        name: Cao xilong
        email: cxlcym@gmail.com
        disqus: cxlcym                              # Disqus缩略标识
        gcse: 008234092874476365914:ygzovwyok10     # Google自定义搜索标识ID
        github: cxlcym                              # GitHub账号
        gravatar: e1235ae56900647c5ec6b73c9a8d9e30  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
